color: teal
fieldLayouts:
  66486ad3-3f58-4576-8629-b2c60d499079:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T09:30:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2226bf20-a955-4ac9-9575-decf1f03f0e9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T09:32:57+00:00'
            elementCondition: null
            fieldUid: e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8 # Plain Text
            handle: subtext
            includeInCards: false
            instructions: null
            label: Subtext
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26c73f35-13df-45e6-8ff1-f0ae58b7a272
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T09:32:57+00:00'
            elementCondition: null
            fieldUid: 35c35080-108d-485f-925f-407a5ab65a22 # Cover
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b55c2e23-2fc0-48e6-b8ea-df3a9fcf445d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 64ab4351-b395-470c-949f-936b3a7daf55
        userCondition: null
handle: categories
hasTitleField: true
icon: film
name: Categories
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
